@server = http://localhost:8000
@letterNo = 1
@postNo = 1

### 내 편지함 출력
GET {{server}}/MyLetter/{{letterNo}}


### 편지내용 보기
POST {{server}}/MyLetter/{{letterNo}}/{{postNo}}

### 편지내용 삭제
DELETE {{server}}/MyLetter/{{letterNo}}/{{postNo}}/delete


### 좋아요 클릭시 좋아요 숫자 1증가
PATCH  {{server}}/MyLetter/{{letterNo}}/{{postNo}}/likes
Content-Type: application/json; charset=utf-8

{
    "number": 2
}